version: "3.8"
services:
  server:
    image: library-server
    restart: always
    ports:
      - 9090:8080
    environment:
      - SPRING_PROFILES_ACTIVE=mysql
    depends_on:
      - mysqldb
  mysqldb:
    image: "mysql"
    restart: always
    container_name: mysqldb
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE="${MYSQL_DATABASE}"
      - MYSQL_ROOT_PASSWORD="${MYSQL_ROOT_PASSWORD}"
      - MYSQL_USER="${MYSQL_USER}"
      - MYSQL_PASSWORD="${MYSQL_PASSWORD}"
    volumes:
      - db:/var/lib/mysql
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local