version: "3.8"
services:
  server:
    image: library-server
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=postgres
    depends_on:
      - postgres
    networks:
      - backend
  postgres:
    image: "postgres:13.1-alpine"
    restart: always
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db:/var/lib/postgresql
    networks:
      - backend
volumes:
  db:

networks:
  backend: