version: "3.8"
services:
  server:
#    build: .
    image: library-server
    restart: always
    ports:
      - 9090:8080
#    depends_on:
#      - mysqldb
#  mysqldb:
#    image: "mysql:5.7"
#    restart: always
#    ports:
#      - 3307:3306
#    env_file:
#      - .env
